version: '3.8'

services:
  mariadb-server:
    build:
      context: .
    image: mariadb-server
    container_name: mariadb-server1
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: m1_s3cr3t
